<?php
$title = 'Categories';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p><a href="<?php echo $this->url('category', array('action'=>'add'));?>">Add new category</a></p>
<table class="table table-bordered table-hover">
    <tr>
        <th>Category</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach($categories as $category) : ?>
	    <tr>
	        <td><?php echo $this->escapeHtml($category->getName());?></td>
	        <td>
	            <a href="<?php echo $this->url('category', array('action' => 'edit', 'id' => $category->getId())); ?>">Edit</a>
	        </td>
	        <td>
	            <a href="<?php echo $this->url('category', array('action' => 'delete', 'id' => $category->getId())); ?>" onclick="return confirm('Are you sure?')">Delete</a>
	        </td>
	    </tr>
    <?php endforeach; ?>
</table>